2025-06-13 23:09:18,400 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-13 23:09:18,400 INFO: [33mPress CTRL+C to quit[0m
2025-06-13 23:09:24,633 ERROR: Exception on /admin/add [POST]
Traceback (most recent call last):
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\routes.py", line 215, in add_farm
    nuevo_farm = Farm(
                 ^^^^^
  File "<string>", line 4, in __init__
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\state.py", line 571, in _initialize_instance
    with util.safe_reraise():
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\state.py", line 569, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 2173, in _declarative_constructor
    raise TypeError(
TypeError: 'creado_por' is an invalid keyword argument for Farm
2025-06-13 23:09:24,916 INFO: 127.0.0.1 - - [13/Jun/2025 23:09:24] "[35m[1mPOST /admin/add HTTP/1.1[0m" 500 -
2025-06-13 23:09:34,704 ERROR: Exception on /admin/add [POST]
Traceback (most recent call last):
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\routes.py", line 215, in add_farm
    nuevo_farm = Farm(
                 ^^^^^
  File "<string>", line 4, in __init__
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\state.py", line 571, in _initialize_instance
    with util.safe_reraise():
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\state.py", line 569, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 2173, in _declarative_constructor
    raise TypeError(
TypeError: 'creado_por' is an invalid keyword argument for Farm
2025-06-13 23:09:34,983 INFO: 127.0.0.1 - - [13/Jun/2025 23:09:34] "[35m[1mPOST /admin/add HTTP/1.1[0m" 500 -
2025-06-13 23:09:43,747 INFO: 127.0.0.1 - - [13/Jun/2025 23:09:43] "GET /admin/add HTTP/1.1" 200 -
2025-06-13 23:09:55,775 ERROR: Exception on /admin/add [POST]
Traceback (most recent call last):
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\routes.py", line 215, in add_farm
    nuevo_farm = Farm(
                 ^^^^^
  File "<string>", line 4, in __init__
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\state.py", line 571, in _initialize_instance
    with util.safe_reraise():
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\state.py", line 569, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 2173, in _declarative_constructor
    raise TypeError(
TypeError: 'creado_por' is an invalid keyword argument for Farm
2025-06-13 23:09:56,055 INFO: 127.0.0.1 - - [13/Jun/2025 23:09:56] "[35m[1mPOST /admin/add HTTP/1.1[0m" 500 -
2025-06-13 23:19:26,145 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-13 23:19:26,146 INFO: [33mPress CTRL+C to quit[0m
2025-06-13 23:19:33,115 INFO: 127.0.0.1 - - [13/Jun/2025 23:19:33] "GET /admin/add HTTP/1.1" 200 -
2025-06-13 23:19:42,617 INFO: 127.0.0.1 - - [13/Jun/2025 23:19:42] "GET /admin/add HTTP/1.1" 200 -
2025-06-13 23:19:56,504 INFO: 127.0.0.1 - - [13/Jun/2025 23:19:56] "[32mPOST /admin/add HTTP/1.1[0m" 302 -
2025-06-13 23:19:56,976 ERROR: Exception on /admin [GET]
Traceback (most recent call last):
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\routes.py", line 157, in admin_panel
    "creado_por": farm.creado_por,
                  ^^^^^^^^^^^^^^^
AttributeError: 'Farm' object has no attribute 'creado_por'
2025-06-13 23:19:57,272 INFO: 127.0.0.1 - - [13/Jun/2025 23:19:57] "[35m[1mGET /admin HTTP/1.1[0m" 500 -
2025-06-13 23:22:23,059 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-13 23:22:23,059 INFO: [33mPress CTRL+C to quit[0m
2025-06-13 23:22:28,478 INFO: 127.0.0.1 - - [13/Jun/2025 23:22:28] "GET /admin/add HTTP/1.1" 200 -
2025-06-13 23:22:32,693 INFO: 127.0.0.1 - - [13/Jun/2025 23:22:32] "GET /admin HTTP/1.1" 200 -
2025-06-13 23:22:37,710 INFO: 127.0.0.1 - - [13/Jun/2025 23:22:37] "[32mPOST /admin/delete/1 HTTP/1.1[0m" 302 -
2025-06-13 23:22:38,448 INFO: 127.0.0.1 - - [13/Jun/2025 23:22:38] "GET /admin HTTP/1.1" 200 -
2025-06-13 23:22:41,349 INFO: 127.0.0.1 - - [13/Jun/2025 23:22:41] "GET /admin/add HTTP/1.1" 200 -
2025-06-13 23:22:56,067 INFO: 127.0.0.1 - - [13/Jun/2025 23:22:56] "[32mPOST /admin/add HTTP/1.1[0m" 302 -
2025-06-13 23:22:56,806 INFO: 127.0.0.1 - - [13/Jun/2025 23:22:56] "GET /admin HTTP/1.1" 200 -
2025-06-13 23:23:03,906 INFO: 127.0.0.1 - - [13/Jun/2025 23:23:03] "GET /admin/create_user HTTP/1.1" 200 -
2025-06-13 23:23:06,558 INFO: 127.0.0.1 - - [13/Jun/2025 23:23:06] "GET /admin/users HTTP/1.1" 200 -
2025-06-13 23:27:14,252 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-13 23:27:14,252 INFO: [33mPress CTRL+C to quit[0m
2025-06-13 23:27:23,996 INFO: 127.0.0.1 - - [13/Jun/2025 23:27:23] "GET /admin/users HTTP/1.1" 200 -
2025-06-13 23:27:26,725 INFO: 127.0.0.1 - - [13/Jun/2025 23:27:26] "[32mPOST /admin/delete_user/3 HTTP/1.1[0m" 302 -
2025-06-13 23:27:27,365 INFO: 127.0.0.1 - - [13/Jun/2025 23:27:27] "GET /admin/users HTTP/1.1" 200 -
2025-06-13 23:28:16,994 INFO: 127.0.0.1 - - [13/Jun/2025 23:28:16] "GET /farms HTTP/1.1" 200 -
2025-06-13 23:28:20,413 ERROR: Exception on /farmeo/2 [GET]
Traceback (most recent call last):
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\routes.py", line 420, in farmeo_detail
    return render_template('farmeo_detail.html', farm=farm)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\templates\farmeo_detail.html", line 55, in top-level template code
    <span class="font-semibold">Ganancia:</span> {{ format_gsc(farm.ganancia) }} \U0001fa99
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'format_gsc' is undefined
2025-06-13 23:28:20,734 INFO: 127.0.0.1 - - [13/Jun/2025 23:28:20] "[35m[1mGET /farmeo/2 HTTP/1.1[0m" 500 -
2025-06-13 23:28:34,067 INFO: 127.0.0.1 - - [13/Jun/2025 23:28:34] "GET /admin HTTP/1.1" 200 -
2025-06-13 23:28:41,773 INFO: 127.0.0.1 - - [13/Jun/2025 23:28:41] "GET /admin HTTP/1.1" 200 -
2025-06-13 23:28:43,502 INFO: 127.0.0.1 - - [13/Jun/2025 23:28:43] "GET /farms HTTP/1.1" 200 -
2025-06-13 23:28:44,786 INFO: 127.0.0.1 - - [13/Jun/2025 23:28:44] "GET / HTTP/1.1" 200 -
2025-06-13 23:28:49,227 INFO: 127.0.0.1 - - [13/Jun/2025 23:28:49] "GET /farms HTTP/1.1" 200 -
2025-06-13 23:30:21,451 INFO: 127.0.0.1 - - [13/Jun/2025 23:30:21] "GET / HTTP/1.1" 200 -
2025-06-13 23:33:08,178 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-13 23:33:08,180 INFO: [33mPress CTRL+C to quit[0m
2025-06-13 23:33:13,590 INFO: 127.0.0.1 - - [13/Jun/2025 23:33:13] "GET / HTTP/1.1" 200 -
2025-06-13 23:33:16,227 INFO: 127.0.0.1 - - [13/Jun/2025 23:33:16] "GET /about HTTP/1.1" 200 -
2025-06-13 23:34:01,276 INFO: 127.0.0.1 - - [13/Jun/2025 23:34:01] "GET /farms HTTP/1.1" 200 -
2025-06-13 23:34:04,260 INFO: 127.0.0.1 - - [13/Jun/2025 23:34:04] "GET /admin/create_user HTTP/1.1" 200 -
2025-06-13 23:34:06,331 INFO: 127.0.0.1 - - [13/Jun/2025 23:34:06] "GET /about HTTP/1.1" 200 -
2025-06-13 23:34:53,294 INFO: 127.0.0.1 - - [13/Jun/2025 23:34:53] "GET / HTTP/1.1" 200 -
2025-06-13 23:37:48,324 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-13 23:37:48,324 INFO: [33mPress CTRL+C to quit[0m
2025-06-13 23:37:54,629 INFO: 127.0.0.1 - - [13/Jun/2025 23:37:54] "GET / HTTP/1.1" 200 -
2025-06-13 23:38:02,386 INFO: 127.0.0.1 - - [13/Jun/2025 23:38:02] "GET /farms HTTP/1.1" 200 -
2025-06-13 23:38:04,316 INFO: 127.0.0.1 - - [13/Jun/2025 23:38:04] "GET / HTTP/1.1" 200 -
2025-06-13 23:45:03,028 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-13 23:45:03,029 INFO: [33mPress CTRL+C to quit[0m
2025-06-13 23:45:06,396 INFO: 127.0.0.1 - - [13/Jun/2025 23:45:06] "GET / HTTP/1.1" 200 -
2025-06-13 23:45:12,749 INFO: 127.0.0.1 - - [13/Jun/2025 23:45:12] "GET / HTTP/1.1" 200 -
2025-06-13 23:45:14,136 INFO: 127.0.0.1 - - [13/Jun/2025 23:45:14] "GET / HTTP/1.1" 200 -
2025-06-13 23:45:15,157 INFO: 127.0.0.1 - - [13/Jun/2025 23:45:15] "GET / HTTP/1.1" 200 -
2025-06-13 23:45:17,067 INFO: 127.0.0.1 - - [13/Jun/2025 23:45:17] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
2025-06-13 23:45:20,420 INFO: 127.0.0.1 - - [13/Jun/2025 23:45:20] "GET / HTTP/1.1" 200 -
2025-06-13 23:45:20,914 INFO: 127.0.0.1 - - [13/Jun/2025 23:45:20] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
2025-06-13 23:47:36,726 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-13 23:47:36,726 INFO: [33mPress CTRL+C to quit[0m
2025-06-13 23:47:42,167 INFO: 127.0.0.1 - - [13/Jun/2025 23:47:42] "GET / HTTP/1.1" 200 -
2025-06-13 23:49:26,258 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-13 23:49:26,259 INFO: [33mPress CTRL+C to quit[0m
2025-06-13 23:49:30,857 INFO: 127.0.0.1 - - [13/Jun/2025 23:49:30] "GET / HTTP/1.1" 200 -
2025-06-13 23:58:23,676 ERROR: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\connections.py", line 744, in _read_packet
    packet_header = self._read_bytes(4)
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\connections.py", line 798, in _read_bytes
    raise err.OperationalError(
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\routes.py", line 101, in index
    farmeos = query.all()
              ^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\query.py", line 2704, in all
    return self._iter().all()  # type: ignore
           ^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\query.py", line 2857, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\context.py", line 306, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1415, in execute
    return meth(
           ^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\connections.py", line 744, in _read_packet
    packet_header = self._read_bytes(4)
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\connections.py", line 798, in _read_bytes
    raise err.OperationalError(
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
[SQL: SELECT farm.id AS farm_id, farm.nombre AS farm_nombre, farm.veces_realizadas AS farm_veces_realizadas, farm.ganancia AS farm_ganancia, farm.waypoint AS farm_waypoint, farm.duracion AS farm_duracion, farm.requerimientos AS farm_requerimientos, farm.profit_hr AS farm_profit_hr, farm.limitation AS farm_limitation 
FROM farm]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-06-13 23:58:23,684 INFO: 127.0.0.1 - - [13/Jun/2025 23:58:23] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-06-13 23:58:23,736 ERROR: Error on request:
Traceback (most recent call last):
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\connections.py", line 744, in _read_packet
    packet_header = self._read_bytes(4)
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\connections.py", line 798, in _read_bytes
    raise err.OperationalError(
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\routes.py", line 101, in index
    farmeos = query.all()
              ^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\query.py", line 2704, in all
    return self._iter().all()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\query.py", line 2857, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\context.py", line 306, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1415, in execute
    return meth(
           ^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\connections.py", line 744, in _read_packet
    packet_header = self._read_bytes(4)
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\pymysql\connections.py", line 798, in _read_bytes
    raise err.OperationalError(
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
[SQL: SELECT farm.id AS farm_id, farm.nombre AS farm_nombre, farm.veces_realizadas AS farm_veces_realizadas, farm.ganancia AS farm_ganancia, farm.waypoint AS farm_waypoint, farm.duracion AS farm_duracion, farm.requerimientos AS farm_requerimientos, farm.profit_hr AS farm_profit_hr, farm.limitation AS farm_limitation 
FROM farm]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\werkzeug\serving.py", line 331, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 860, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\routes.py", line 415, in server_error
    return render_template('500.html'), 500
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 127, in _render
    app.update_template_context(context)
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 530, in update_template_context
    context.update(self.ensure_sync(func)())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask_login\utils.py", line 405, in _user_context_processor
    return dict(current_user=_get_user())
                             ^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask_login\login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\__init__.py", line 54, in load_user
    return User.query.get(int(user_id))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in get
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\util\deprecations.py", line 386, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\query.py", line 1126, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\query.py", line 1135, in _get_impl
    return self.session._get_impl(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3873, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\loading.py", line 694, in load_on_pk_identity
    session.execute(
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\orm\context.py", line 306, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1415, in execute
    return meth(
           ^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1809, in _execute_context
    conn = self._revalidate_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 675, in _revalidate_connection
    self._invalid_transaction()
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 665, in _invalid_transaction
    raise exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-06-13 23:58:27,874 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-13 23:58:27,875 INFO: [33mPress CTRL+C to quit[0m
2025-06-13 23:58:30,882 INFO: 127.0.0.1 - - [13/Jun/2025 23:58:30] "GET / HTTP/1.1" 200 -
2025-06-14 00:04:59,631 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 00:04:59,631 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 00:05:03,101 INFO: 127.0.0.1 - - [14/Jun/2025 00:05:03] "GET / HTTP/1.1" 200 -
2025-06-14 00:05:38,797 INFO: 127.0.0.1 - - [14/Jun/2025 00:05:38] "GET /farms HTTP/1.1" 200 -
2025-06-14 00:05:40,784 INFO: 127.0.0.1 - - [14/Jun/2025 00:05:40] "GET / HTTP/1.1" 200 -
2025-06-14 22:29:36,700 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 22:29:36,701 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 22:29:47,106 INFO: 127.0.0.1 - - [14/Jun/2025 22:29:47] "GET / HTTP/1.1" 200 -
2025-06-14 22:29:47,737 INFO: 127.0.0.1 - - [14/Jun/2025 22:29:47] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-06-14 22:29:51,463 INFO: 127.0.0.1 - - [14/Jun/2025 22:29:51] "GET /farms HTTP/1.1" 200 -
2025-06-14 22:30:53,889 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 22:30:53,889 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 22:30:57,091 INFO: 127.0.0.1 - - [14/Jun/2025 22:30:57] "GET /farms HTTP/1.1" 200 -
2025-06-14 22:31:24,995 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 22:31:24,996 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 22:31:27,785 INFO: 127.0.0.1 - - [14/Jun/2025 22:31:27] "GET /farms HTTP/1.1" 200 -
2025-06-14 22:34:19,017 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 22:34:19,017 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 22:34:23,013 INFO: 127.0.0.1 - - [14/Jun/2025 22:34:23] "GET /farms HTTP/1.1" 200 -
2025-06-14 22:35:20,119 ERROR: Exception on /farmeo/6 [GET]
Traceback (most recent call last):
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\routes.py", line 420, in farmeo_detail
    return render_template('farmeo_detail.html', farm=farm)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\templates\farmeo_detail.html", line 55, in top-level template code
    <span class="font-semibold">Ganancia:</span> {{ format_gsc(farm.ganancia) }} \U0001fa99
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'format_gsc' is undefined
2025-06-14 22:35:20,414 INFO: 127.0.0.1 - - [14/Jun/2025 22:35:20] "[35m[1mGET /farmeo/6 HTTP/1.1[0m" 500 -
2025-06-14 22:35:49,172 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 22:35:49,172 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 22:35:52,728 INFO: 127.0.0.1 - - [14/Jun/2025 22:35:52] "GET /farms HTTP/1.1" 200 -
2025-06-14 22:41:03,169 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 22:41:03,169 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 22:41:08,618 INFO: 127.0.0.1 - - [14/Jun/2025 22:41:08] "GET /farms HTTP/1.1" 200 -
2025-06-14 22:41:12,363 INFO: 127.0.0.1 - - [14/Jun/2025 22:41:12] "GET /farms?nombre=&waypoint=&duracion=&profit_hr_min=&sort=id_asc HTTP/1.1" 200 -
2025-06-14 22:41:14,385 INFO: 127.0.0.1 - - [14/Jun/2025 22:41:14] "GET /farms?nombre=&waypoint=&duracion=&profit_hr_min=&sort=id_desc HTTP/1.1" 200 -
2025-06-14 22:41:17,924 INFO: 127.0.0.1 - - [14/Jun/2025 22:41:17] "GET /farms?nombre=&waypoint=&duracion=&profit_hr_min=&sort=duracion_desc HTTP/1.1" 200 -
2025-06-14 22:41:19,858 INFO: 127.0.0.1 - - [14/Jun/2025 22:41:19] "GET /farms?nombre=&waypoint=&duracion=&profit_hr_min=&sort=id_desc HTTP/1.1" 200 -
2025-06-14 22:41:33,442 INFO: 127.0.0.1 - - [14/Jun/2025 22:41:33] "GET /auth/login HTTP/1.1" 200 -
2025-06-14 22:41:36,192 INFO: 127.0.0.1 - - [14/Jun/2025 22:41:36] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
2025-06-14 22:41:36,806 INFO: 127.0.0.1 - - [14/Jun/2025 22:41:36] "GET / HTTP/1.1" 200 -
2025-06-14 22:41:58,585 INFO: 127.0.0.1 - - [14/Jun/2025 22:41:58] "GET /farms HTTP/1.1" 200 -
2025-06-14 22:43:53,591 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 22:43:53,591 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 22:43:56,553 ERROR: Exception on /farms [GET]
Traceback (most recent call last):
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\routes.py", line 561, in farms
    return render_template('farms.html',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\templates\farms.html", line 31, in top-level template code
    <a href="{{ url_for('main.daily_routine') }}" class="flex items-center gap-3 px-4 py-2 hover:bg-indigo-800 rounded transition-all">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.daily_routine'. Did you mean 'main.about' instead?
2025-06-14 22:43:56,890 INFO: 127.0.0.1 - - [14/Jun/2025 22:43:56] "[35m[1mGET /farms HTTP/1.1[0m" 500 -
2025-06-14 22:43:59,302 INFO: 127.0.0.1 - - [14/Jun/2025 22:43:59] "GET / HTTP/1.1" 200 -
2025-06-14 22:44:00,626 ERROR: Exception on /farms [GET]
Traceback (most recent call last):
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\routes.py", line 561, in farms
    return render_template('farms.html',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\templates\farms.html", line 31, in top-level template code
    <a href="{{ url_for('main.daily_routine') }}" class="flex items-center gap-3 px-4 py-2 hover:bg-indigo-800 rounded transition-all">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.daily_routine'. Did you mean 'main.about' instead?
2025-06-14 22:44:00,920 INFO: 127.0.0.1 - - [14/Jun/2025 22:44:00] "[35m[1mGET /farms HTTP/1.1[0m" 500 -
2025-06-14 22:44:40,813 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 22:44:40,813 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 22:44:45,346 ERROR: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\routes.py", line 120, in index
    return render_template('index.html', farmeos=farmeos_formateados, total_farmeos=total_farmeos, suma_ganancias=suma_ganancias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\templates\index.html", line 32, in top-level template code
    <a href="{{ url_for('main.daily_routine') }}" class="flex items-center gap-3 px-4 py-2 hover:bg-indigo-800 rounded transition-all">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.daily_routine'. Did you mean 'main.about' instead?
2025-06-14 22:44:45,628 INFO: 127.0.0.1 - - [14/Jun/2025 22:44:45] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-06-14 22:45:01,757 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 22:45:01,757 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 22:45:04,933 ERROR: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\routes.py", line 120, in index
    return render_template('index.html', farmeos=farmeos_formateados, total_farmeos=total_farmeos, suma_ganancias=suma_ganancias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\templates\index.html", line 32, in top-level template code
    <a href="{{ url_for('main.daily_routine') }}" class="flex items-center gap-3 px-4 py-2 hover:bg-indigo-800 rounded transition-all">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.daily_routine'. Did you mean 'main.about' instead?
2025-06-14 22:45:05,229 INFO: 127.0.0.1 - - [14/Jun/2025 22:45:05] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-06-14 22:45:27,197 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 22:45:27,197 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 22:45:30,670 INFO: 127.0.0.1 - - [14/Jun/2025 22:45:30] "GET / HTTP/1.1" 200 -
2025-06-14 22:46:33,107 INFO: 127.0.0.1 - - [14/Jun/2025 22:46:33] "GET /farms HTTP/1.1" 200 -
2025-06-14 22:47:22,836 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 22:47:22,836 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 22:47:26,209 INFO: 127.0.0.1 - - [14/Jun/2025 22:47:26] "GET /farms HTTP/1.1" 200 -
2025-06-14 22:47:28,261 INFO: 127.0.0.1 - - [14/Jun/2025 22:47:28] "GET / HTTP/1.1" 200 -
2025-06-14 22:47:30,446 INFO: 127.0.0.1 - - [14/Jun/2025 22:47:30] "GET / HTTP/1.1" 200 -
2025-06-14 22:47:38,670 INFO: 127.0.0.1 - - [14/Jun/2025 22:47:38] "GET / HTTP/1.1" 200 -
2025-06-14 22:47:42,545 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 22:47:42,546 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 22:47:46,220 INFO: 127.0.0.1 - - [14/Jun/2025 22:47:46] "GET / HTTP/1.1" 200 -
2025-06-14 22:48:13,369 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 22:48:13,369 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 22:48:16,295 ERROR: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\routes.py", line 120, in index
    return render_template('index.html', farmeos=farmeos_formateados, total_farmeos=total_farmeos, suma_ganancias=suma_ganancias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\templates\index.html", line 32, in top-level template code
    <a href="{{ url_for('main.daily_routine') }}" class="flex items-center gap-3 px-4 py-2 hover:bg-indigo-800 rounded transition-all">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.daily_routine'. Did you mean 'main.about' instead?
2025-06-14 22:48:16,595 INFO: 127.0.0.1 - - [14/Jun/2025 22:48:16] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-06-14 22:49:07,910 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 22:49:07,910 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 22:49:11,066 ERROR: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\routes.py", line 120, in index
    return render_template('index.html', farmeos=farmeos_formateados, total_farmeos=total_farmeos, suma_ganancias=suma_ganancias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\templates\index.html", line 32, in top-level template code
    <a href="{{ url_for('main.daily_routine') }}" @click="if(window.innerWidth<768){sidebarOpen=false}" class="flex items-center gap-3 px-4 py-2 hover:bg-indigo-800 rounded transition-all">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.daily_routine'. Did you mean 'main.about' instead?
2025-06-14 22:49:11,364 INFO: 127.0.0.1 - - [14/Jun/2025 22:49:11] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-06-14 22:49:51,502 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 22:49:51,502 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 22:49:54,911 ERROR: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\routes.py", line 120, in index
    return render_template('index.html', farmeos=farmeos_formateados, total_farmeos=total_farmeos, suma_ganancias=suma_ganancias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\templates\index.html", line 32, in top-level template code
    <a href="{{ url_for('main.daily_routine') }}" class="flex items-center gap-3 px-4 py-2 hover:bg-indigo-800 rounded transition-all">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.daily_routine'. Did you mean 'main.about' instead?
2025-06-14 22:49:55,216 INFO: 127.0.0.1 - - [14/Jun/2025 22:49:55] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-06-14 22:50:05,739 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 22:50:05,739 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 22:50:09,677 ERROR: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\routes.py", line 120, in index
    return render_template('index.html', farmeos=farmeos_formateados, total_farmeos=total_farmeos, suma_ganancias=suma_ganancias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\templates\index.html", line 32, in top-level template code
    <a href="{{ url_for('main.daily_routine') }}" class="flex items-center gap-3 px-4 py-2 hover:bg-indigo-800 rounded transition-all">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.daily_routine'. Did you mean 'main.about' instead?
2025-06-14 22:50:09,957 INFO: 127.0.0.1 - - [14/Jun/2025 22:50:09] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-06-14 22:50:23,303 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 22:50:23,303 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 22:50:26,740 INFO: 127.0.0.1 - - [14/Jun/2025 22:50:26] "GET / HTTP/1.1" 200 -
2025-06-14 22:51:26,586 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 22:51:26,586 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 22:51:31,116 ERROR: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\routes.py", line 120, in index
    return render_template('index.html', farmeos=farmeos_formateados, total_farmeos=total_farmeos, suma_ganancias=suma_ganancias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\templates\index.html", line 32, in top-level template code
    <a href="{{ url_for('main.daily_routine') }}" @click="if(window.innerWidth<768){sidebarOpen=false}" class="flex items-center gap-3 px-4 py-2 hover:bg-indigo-800 rounded transition-all">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.daily_routine'. Did you mean 'main.about' instead?
2025-06-14 22:51:31,435 INFO: 127.0.0.1 - - [14/Jun/2025 22:51:31] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-06-14 22:53:38,594 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 22:53:38,594 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 22:53:42,613 INFO: 127.0.0.1 - - [14/Jun/2025 22:53:42] "GET / HTTP/1.1" 200 -
2025-06-14 22:53:46,563 ERROR: Exception on /daily-routine [GET]
Traceback (most recent call last):
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\routes.py", line 584, in daily_routine
    return render_template('daily_routine.html', farmeos=farmeos_formateados)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\templates\daily_routine.html", line 27, in top-level template code
    <form method="POST" action="{{ url_for('main.set_daily_routine') }}" class="bg-white/10 backdrop-blur-lg rounded-lg p-6">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.set_daily_routine'. Did you mean 'main.daily_routine' instead?
2025-06-14 22:53:46,860 INFO: 127.0.0.1 - - [14/Jun/2025 22:53:46] "[35m[1mGET /daily-routine HTTP/1.1[0m" 500 -
2025-06-14 22:55:57,227 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 22:55:57,227 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 22:56:01,635 ERROR: Exception on /daily-routine [GET]
Traceback (most recent call last):
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\routes.py", line 584, in daily_routine
    return render_template('daily_routine.html', farmeos=farmeos_formateados)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\templates\daily_routine.html", line 27, in top-level template code
    <form method="POST" action="{{ url_for('main.set_daily_routine') }}" class="bg-white/10 backdrop-blur-lg rounded-lg p-6">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.set_daily_routine'. Did you mean 'main.daily_routine' instead?
2025-06-14 22:56:01,933 INFO: 127.0.0.1 - - [14/Jun/2025 22:56:01] "[35m[1mGET /daily-routine HTTP/1.1[0m" 500 -
2025-06-14 22:59:02,272 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 22:59:02,272 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 22:59:06,100 ERROR: Exception on /daily-routine [GET]
Traceback (most recent call last):
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\routes.py", line 586, in daily_routine
    return render_template('daily_routine.html', farmeos=farmeos_formateados)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Kunzeu\Desktop\Gold Making\app\templates\daily_routine.html", line 27, in top-level template code
    <form method="POST" action="{{ url_for('main.set_daily_routine') }}" class="bg-white/10 backdrop-blur-lg rounded-lg p-6">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kunzeu\Desktop\Gold Making\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.set_daily_routine'. Did you mean 'main.daily_routine' instead?
2025-06-14 22:59:06,394 INFO: 127.0.0.1 - - [14/Jun/2025 22:59:06] "[35m[1mGET /daily-routine HTTP/1.1[0m" 500 -
2025-06-14 23:02:56,431 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 23:02:56,432 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 23:03:01,130 INFO: 127.0.0.1 - - [14/Jun/2025 23:03:01] "GET /daily-routine HTTP/1.1" 200 -
2025-06-14 23:03:07,917 INFO: 127.0.0.1 - - [14/Jun/2025 23:03:07] "[32mPOST /set-daily-routine HTTP/1.1[0m" 302 -
2025-06-14 23:03:08,487 INFO: 127.0.0.1 - - [14/Jun/2025 23:03:08] "GET /daily-routine HTTP/1.1" 200 -
2025-06-14 23:03:10,802 INFO: 127.0.0.1 - - [14/Jun/2025 23:03:10] "GET /daily-routine HTTP/1.1" 200 -
2025-06-14 23:03:12,563 INFO: 127.0.0.1 - - [14/Jun/2025 23:03:12] "GET / HTTP/1.1" 200 -
2025-06-14 23:03:18,128 INFO: 127.0.0.1 - - [14/Jun/2025 23:03:18] "GET /farms HTTP/1.1" 200 -
2025-06-14 23:03:22,185 INFO: 127.0.0.1 - - [14/Jun/2025 23:03:22] "GET / HTTP/1.1" 200 -
2025-06-14 23:03:23,718 INFO: 127.0.0.1 - - [14/Jun/2025 23:03:23] "GET /farms HTTP/1.1" 200 -
2025-06-14 23:03:25,107 INFO: 127.0.0.1 - - [14/Jun/2025 23:03:25] "GET / HTTP/1.1" 200 -
2025-06-14 23:03:26,811 INFO: 127.0.0.1 - - [14/Jun/2025 23:03:26] "GET /farms HTTP/1.1" 200 -
2025-06-14 23:03:29,499 INFO: 127.0.0.1 - - [14/Jun/2025 23:03:29] "GET /admin HTTP/1.1" 200 -
2025-06-14 23:03:30,819 INFO: 127.0.0.1 - - [14/Jun/2025 23:03:30] "GET / HTTP/1.1" 200 -
2025-06-14 23:03:43,819 INFO: 127.0.0.1 - - [14/Jun/2025 23:03:43] "GET /farms HTTP/1.1" 200 -
2025-06-14 23:04:42,955 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 23:04:42,956 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 23:04:46,664 INFO: 127.0.0.1 - - [14/Jun/2025 23:04:46] "GET /farms HTTP/1.1" 200 -
2025-06-14 23:04:47,939 INFO: 127.0.0.1 - - [14/Jun/2025 23:04:47] "GET /daily-routine HTTP/1.1" 200 -
2025-06-14 23:06:27,434 INFO: 127.0.0.1 - - [14/Jun/2025 23:06:27] "[32mPOST /set-daily-routine HTTP/1.1[0m" 302 -
2025-06-14 23:06:28,028 INFO: 127.0.0.1 - - [14/Jun/2025 23:06:28] "GET /daily-routine HTTP/1.1" 200 -
2025-06-14 23:06:31,871 INFO: 127.0.0.1 - - [14/Jun/2025 23:06:31] "GET /daily-routine HTTP/1.1" 200 -
2025-06-14 23:06:33,320 INFO: 127.0.0.1 - - [14/Jun/2025 23:06:33] "GET /farms HTTP/1.1" 200 -
2025-06-14 23:06:37,597 INFO: 127.0.0.1 - - [14/Jun/2025 23:06:37] "GET / HTTP/1.1" 200 -
2025-06-14 23:06:41,234 INFO: 127.0.0.1 - - [14/Jun/2025 23:06:41] "GET /admin/create_user HTTP/1.1" 200 -
2025-06-14 23:06:43,561 INFO: 127.0.0.1 - - [14/Jun/2025 23:06:43] "GET /farms HTTP/1.1" 200 -
2025-06-14 23:06:45,576 INFO: 127.0.0.1 - - [14/Jun/2025 23:06:45] "GET /daily-routine HTTP/1.1" 200 -
2025-06-14 23:10:36,006 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 23:10:36,006 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 23:10:40,732 INFO: 127.0.0.1 - - [14/Jun/2025 23:10:40] "GET /daily-routine HTTP/1.1" 200 -
2025-06-14 23:12:07,393 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 23:12:07,393 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 23:12:10,645 INFO: 127.0.0.1 - - [14/Jun/2025 23:12:10] "GET /daily-routine HTTP/1.1" 200 -
2025-06-14 23:12:13,173 INFO: 127.0.0.1 - - [14/Jun/2025 23:12:13] "GET / HTTP/1.1" 200 -
2025-06-14 23:12:16,444 INFO: 127.0.0.1 - - [14/Jun/2025 23:12:16] "GET /daily-routine HTTP/1.1" 200 -
2025-06-14 23:12:18,233 INFO: 127.0.0.1 - - [14/Jun/2025 23:12:18] "GET / HTTP/1.1" 200 -
2025-06-14 23:12:19,378 INFO: 127.0.0.1 - - [14/Jun/2025 23:12:19] "GET /farms HTTP/1.1" 200 -
2025-06-14 23:12:45,122 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 23:12:45,122 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 23:12:48,889 INFO: 127.0.0.1 - - [14/Jun/2025 23:12:48] "GET /about HTTP/1.1" 200 -
2025-06-14 23:12:52,835 INFO: 127.0.0.1 - - [14/Jun/2025 23:12:52] "GET /farms HTTP/1.1" 200 -
2025-06-14 23:12:55,496 INFO: 127.0.0.1 - - [14/Jun/2025 23:12:55] "GET /admin HTTP/1.1" 200 -
2025-06-14 23:13:07,838 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 23:13:07,838 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 23:13:11,635 INFO: 127.0.0.1 - - [14/Jun/2025 23:13:11] "GET /daily-routine HTTP/1.1" 200 -
2025-06-14 23:13:18,669 INFO: 127.0.0.1 - - [14/Jun/2025 23:13:18] "GET / HTTP/1.1" 200 -
2025-06-14 23:13:20,523 INFO: 127.0.0.1 - - [14/Jun/2025 23:13:20] "GET /daily-routine HTTP/1.1" 200 -
2025-06-14 23:13:43,115 INFO: 127.0.0.1 - - [14/Jun/2025 23:13:43] "GET /admin HTTP/1.1" 200 -
2025-06-14 23:13:45,217 INFO: 127.0.0.1 - - [14/Jun/2025 23:13:45] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
2025-06-14 23:14:14,615 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 23:14:14,616 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 23:14:17,597 INFO: 127.0.0.1 - - [14/Jun/2025 23:14:17] "GET /admin HTTP/1.1" 200 -
2025-06-14 23:15:44,375 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 23:15:44,376 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 23:15:47,971 INFO: 127.0.0.1 - - [14/Jun/2025 23:15:47] "GET /admin HTTP/1.1" 200 -
2025-06-14 23:15:49,714 INFO: 127.0.0.1 - - [14/Jun/2025 23:15:49] "GET / HTTP/1.1" 200 -
2025-06-14 23:15:55,264 INFO: 127.0.0.1 - - [14/Jun/2025 23:15:55] "GET /farms HTTP/1.1" 200 -
2025-06-14 23:15:56,828 INFO: 127.0.0.1 - - [14/Jun/2025 23:15:56] "GET /daily-routine HTTP/1.1" 200 -
2025-06-14 23:15:58,600 INFO: 127.0.0.1 - - [14/Jun/2025 23:15:58] "GET /about HTTP/1.1" 200 -
2025-06-14 23:16:01,796 INFO: 127.0.0.1 - - [14/Jun/2025 23:16:01] "GET /admin HTTP/1.1" 200 -
2025-06-14 23:18:27,950 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 23:18:27,950 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 23:18:31,214 INFO: 127.0.0.1 - - [14/Jun/2025 23:18:31] "GET /admin HTTP/1.1" 200 -
2025-06-14 23:19:11,714 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000
2025-06-14 23:19:11,714 INFO: [33mPress CTRL+C to quit[0m
2025-06-14 23:19:14,617 INFO: 127.0.0.1 - - [14/Jun/2025 23:19:14] "GET /admin HTTP/1.1" 200 -
2025-06-14 23:19:16,820 INFO: 127.0.0.1 - - [14/Jun/2025 23:19:16] "GET / HTTP/1.1" 200 -
2025-06-14 23:19:19,249 INFO: 127.0.0.1 - - [14/Jun/2025 23:19:19] "[32mGET /auth/logout HTTP/1.1[0m" 302 -
2025-06-14 23:19:19,670 INFO: 127.0.0.1 - - [14/Jun/2025 23:19:19] "GET / HTTP/1.1" 200 -
2025-06-14 23:19:20,772 INFO: 127.0.0.1 - - [14/Jun/2025 23:19:20] "GET /daily-routine HTTP/1.1" 200 -
